---
- name: config firewalld(zabbix port)
  firewalld:
    port: 10050-10051/tcp
    permanent: yes
    state: enabled
  become: yes

- name: config firewalld(http)
  firewalld:
    service: http
    permanent: yes
    state: enabled
  become: yes
  notify:
    - restart_firewalld
