---
- name: Make sure pymysql is present
  pip:
    name: pymysql
    state: present
  notify:
    - create_mysql_database
    - create_mysql_user

- name: Zabbix yum repository
  yum:
    name: "{{ repo_base_url }}"

- name: latest Zabbix version installed
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-agent
  notify:
    - init_mysql_for_zabbix
    - edit_zabbix_server.conf_1
    - edit_zabbix_server.conf_2
    - edit_zabbix_server.conf_3
    - edit_zabbix.conf
    - restart_zabbix-server
    - restart_zabbix-agent
    - restart_httpd
    - restart_php-fpm
