---
repo_base_url: https://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-2.el8.noarch.rpm
packages:
  - zabbix-server-mysql
  - zabbix-web-mysql
  - zabbix-agent
mysql_db_name: zabbix
mysql_user_name: zabbix
mysql_user_password: PASSWORD
mysql_user_priv: '*.*:ALL,GRANT'
timezone: Azia/Tokyo
